_target_: wordplay.configs.TrainConfig

framework: pytorch          # ML framework to use: one of 'pytorch', 'tensorflow'
backend: 'DDP'              # Backend to use for distributed training
# ds_config_path: null
device: null
port: null
seed: null
ngpus: null
precision: null
use_wandb: true
wandb_project: WordPlay
eval_interval: 250
log_interval: 100
eval_iters: 200
eval_only: false
always_save_checkpoint: false
init_from: scratch
max_iters: 5000
warmup_iters: 100
dtype: bfloat16
compile: true
