_target_: wordplay.configs.OptimizerConfig

learning_rate: 0.001
weight_decay: 0.1
beta1: 0.9
beta2: 0.99
grad_clip: 1.0
decay_lr: true
lr_decay_iters: 5000
min_lr: 0.0001
gradient_accumulation_steps: null
