_target_: wordplay.configs.GPTModelConfig
# n_layer=36, n_head=20, n_embd=1280
# 774M parameters
n_layer: 36
n_head: 20
n_embd: 1280
batch_size: 4
block_size: 1024
dropout: 0.0
bias: false
vocab_size: null
